/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BaseLayoutImport } from './routes/_base-layout'
import { Route as AnotherLayoutImport } from './routes/_another-layout'
import { Route as BaseLayoutNestedLayoutImport } from './routes/_base-layout/_nested-layout'
import { Route as AnotherLayoutNewsIdImport } from './routes/_another-layout/news/$id'

// Create Virtual Routes

const BaseLayoutIndexLazyImport = createFileRoute('/_base-layout/')()
const BaseLayoutAboutLazyImport = createFileRoute('/_base-layout/about')()
const AnotherLayoutNewsIndexLazyImport = createFileRoute(
  '/_another-layout/news/',
)()
const BaseLayoutNestedLayoutNestedLazyImport = createFileRoute(
  '/_base-layout/_nested-layout/nested',
)()

// Create/Update Routes

const BaseLayoutRoute = BaseLayoutImport.update({
  id: '/_base-layout',
  getParentRoute: () => rootRoute,
} as any)

const AnotherLayoutRoute = AnotherLayoutImport.update({
  id: '/_another-layout',
  getParentRoute: () => rootRoute,
} as any)

const BaseLayoutIndexLazyRoute = BaseLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => BaseLayoutRoute,
} as any).lazy(() =>
  import('./routes/_base-layout/index.lazy').then((d) => d.Route),
)

const BaseLayoutAboutLazyRoute = BaseLayoutAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => BaseLayoutRoute,
} as any).lazy(() =>
  import('./routes/_base-layout/about.lazy').then((d) => d.Route),
)

const BaseLayoutNestedLayoutRoute = BaseLayoutNestedLayoutImport.update({
  id: '/_nested-layout',
  getParentRoute: () => BaseLayoutRoute,
} as any)

const AnotherLayoutNewsIndexLazyRoute = AnotherLayoutNewsIndexLazyImport.update(
  {
    path: '/news/',
    getParentRoute: () => AnotherLayoutRoute,
  } as any,
).lazy(() =>
  import('./routes/_another-layout/news/index.lazy').then((d) => d.Route),
)

const BaseLayoutNestedLayoutNestedLazyRoute =
  BaseLayoutNestedLayoutNestedLazyImport.update({
    path: '/nested',
    getParentRoute: () => BaseLayoutNestedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_base-layout/_nested-layout/nested.lazy').then(
      (d) => d.Route,
    ),
  )

const AnotherLayoutNewsIdRoute = AnotherLayoutNewsIdImport.update({
  path: '/news/$id',
  getParentRoute: () => AnotherLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_another-layout': {
      preLoaderRoute: typeof AnotherLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_base-layout': {
      preLoaderRoute: typeof BaseLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_base-layout/_nested-layout': {
      preLoaderRoute: typeof BaseLayoutNestedLayoutImport
      parentRoute: typeof BaseLayoutImport
    }
    '/_base-layout/about': {
      preLoaderRoute: typeof BaseLayoutAboutLazyImport
      parentRoute: typeof BaseLayoutImport
    }
    '/_base-layout/': {
      preLoaderRoute: typeof BaseLayoutIndexLazyImport
      parentRoute: typeof BaseLayoutImport
    }
    '/_another-layout/news/$id': {
      preLoaderRoute: typeof AnotherLayoutNewsIdImport
      parentRoute: typeof AnotherLayoutImport
    }
    '/_base-layout/_nested-layout/nested': {
      preLoaderRoute: typeof BaseLayoutNestedLayoutNestedLazyImport
      parentRoute: typeof BaseLayoutNestedLayoutImport
    }
    '/_another-layout/news/': {
      preLoaderRoute: typeof AnotherLayoutNewsIndexLazyImport
      parentRoute: typeof AnotherLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AnotherLayoutRoute.addChildren([
    AnotherLayoutNewsIdRoute,
    AnotherLayoutNewsIndexLazyRoute,
  ]),
  BaseLayoutRoute.addChildren([
    BaseLayoutNestedLayoutRoute.addChildren([
      BaseLayoutNestedLayoutNestedLazyRoute,
    ]),
    BaseLayoutAboutLazyRoute,
    BaseLayoutIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
